name: cims
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk:  ">=3.4.3 <4.0.0"

dependencies:
  external_path: ^2.2.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  geolocator: ^13.0.4
  geolocator_android: ^4.6.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1
  http: ^1.4.0
  logger: ^2.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
